version: 0.2

environment_variables:
  plaintext:
    BUCKET_NAME: "YOUR_AWS_REGION_CODE"
    HUGO_VERSION: "0.17"
    HUGO_SHA256: "f1467e204cc469b9ca6f17c0dc4da4a620643b6d9a50cb7dce2508aaf8fbc1ea"


phases:
  install:
    commands:
       - gem install asciidoctor
       - wget https://github.com/gohugoio/hugo/releases/download/v0.31.1/hugo_0.31.1_Linux-64bit.deb
       - dpkg -i hugo*.deb
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      - hugo
      # - command
  post_build:
    commands:
      - aws s3 sync --delete public s3://${BUCKET_NAME} --cache-control max-age=3600
