baseURL = "https://podviaznikov.com"
languageCode = "en-us"
title = "My new site!"
theme = "montaigne"

[params]
author = "Anton Podviaznikov"
author_email = "anton@podviaznikov.com"
tagline = "Hello World!!!"
license = "Attribution, non-commercial"
logo_text_color = "#000"
logo_text_classname = "black"
logo_bg_color = "#ff80cc"
logo_bg_classname = "pink"
[taxonomies]
color = "colors"
license = "licenses"
location = "locations"
person = "people"
tag = "tags"
