baseURL = "http://anton.montaigne.io"
languageCode = "en-us"
title = "Anton Podviaznikov: personal site"
theme = "montaigne"

[params]
author = "Anton Podviaznikov"
author_email = "anton@podviaznikov.com"
tagline = "observer; no answers, only questions"
license = "Attribution"
logo_text_color = "#333"
logo_text_classname = "dark-gray"
logo_bg_color = "#e8fdf5"
logo_bg_classname = "washed-green"

[menu]
[[menu.main]]
name = "pages"
identifier = "pages"
url = "/pages"
[[menu.main]]
name = "writings"
identifier = "writings"
url = "/writings"

[taxonomies]
color = "colors"
license = "licenses"
location = "locations"
person = "people"
tag = "tags"
