baseURL = "http://example.org/"
languageCode = "en-us"
title = "podviaznikov"
theme = "montaigne"
[[menu.now]]
    name = "now"
    weight = -1
    identifier = "now"
    url = "/now/"
[params]
  author = "Anton Podviaznikov"
  tagline = "programmer, observer, citizen of the world"
  authorEmail = "anton@podviaznikov.com"

[taxonomies]
  tag = "tags"
  place = "places"
  person = "people"
  location = "locations"
