baseURL = "https://podviaznikov.com"
languageCode = "en-us"
title = "My new site!"
theme = "montaigne"

[params]
author = "Anton Podviaznikov"
authorEmail = "anton@podviaznikov.com"
tagline = "Hello World1"
license = "Attribution, non-commercial"
logo_text_color = ""
logo_text_classname = ""
logo_bg_color = "#ff4136"
logo_bg_classname = "red"
[taxonomies]color = "colors"
license = "licenses"
location = "locations"
person = "people"
tag = "tags"
