baseURL = "antonpodviaznikov.com"
languageCode = "en-us"
title = "podviaznikov"
theme = "montaigne"

[params]
author = "Anton Podviaznikov"
author_email = "podviaznikov@gmail.com"
tagline = "Personal site"
license = "Attribution, non-commercial"
logo_text_color = ""
logo_text_classname = ""
logo_bg_color = ""
logo_bg_classname = ""
[taxonomies]
color = "colors"
license = "licenses"
location = "locations"
person = "people"
tag = "tags"
