baseURL = "demo037.montaigne.io"
languageCode = "en-us"
title = ""
theme = "montaigne"

[params]
author = "Anton Podviaznikov"
author_email = "podviaznikov@gmail.com"
tagline = ""
license = ""
logo_text_color = "#19a974"
logo_text_classname = "green"
logo_bg_color = "#ff80cc"
logo_bg_classname = "pink"
[taxonomies]
color = "colors"
license = "licenses"
location = "locations"
person = "people"
tag = "tags"
