baseURL = "https://podviaznikov.com"
languageCode = "en-us"
title = "My new site!"
theme = "montaigne"

[params]
author = "Anton Podviaznikov"
authorEmail = "anton@podviaznikov.com"
tagline = "Hello222"
[taxonomies]color = "colors"
license = "licenses"
location = "locations"
person = "people"
tag = "tags"
