baseURL = "http://demo063.montaigne.io"
languageCode = "en-us"
title = "My site"
theme = "montaigne"

[params]
author = "Anton Podviaznikov"
author_email = "anton@podviaznikov.com"
tagline = ""
license = ""
logo_text_color = "#fff"
logo_text_classname = "white"
logo_bg_color = "#000"
logo_bg_classname = "black"

[menu]
[[menu.main]]
name = "writings"
identifier = "writings"
url = "/writings"

[taxonomies]
color = "colors"
license = "licenses"
location = "locations"
person = "people"
tag = "tags"
