baseURL = "https://podviaznikov.com"
languageCode = "en-us"
title = "Anton Podviaznikov: personal site"
theme = "montaigne"

[params]
author = "Anton Podviaznikov"
author_email = "anton@podviaznikov.com"
tagline = "observer; no answers, only questions"
license = "Attribution"
logo_text_color = "#333"
logo_text_classname = "dark-gray"
logo_bg_color = "#e8fdf5"
logo_bg_classname = "washed-green"

[menu]
[[menu.main]]
identifier = "pages"
url = "/pages"
name = "Some information about me"
[[menu.main]]
identifier = "writings"
url = "/writings"
name = "My essays"
[[menu.main]]
identifier = "readings"
url = "/readings"
name = "Books I have read in the last couple of years"
[[menu.main]]
identifier = "poems"
url = "/poems"
name = "Experiments with poetry"
[[menu.main]]
identifier = "dialogues"
url = "/dialogues"
name = "Dialogues with people about books and not only"
[[menu.main]]
identifier = "розмови"
url = "/rozmovy"
name = "Розмови з людиною"


[taxonomies]
color = "colors"
license = "licenses"
location = "locations"
person = "people"
tag = "tags"
