baseURL = "demo037.montaigne.io"
languageCode = "en-us"
title = "Title"
theme = "montaigne"

[params]
author = "Anton Podviaznikov"
author_email = "anton@podviaznikov.com"
tagline = "Site description"
license = ""
logo_text_color = "#19a974"
logo_text_classname = "green"
logo_bg_color = "#e8fdf5"
logo_bg_classname = "washed-green"
[taxonomies]
color = "colors"
license = "licenses"
location = "locations"
person = "people"
tag = "tags"
