baseURL = "http://demo037.montaigne.io"
languageCode = "en-us"
title = "Title"
theme = "montaigne"

[params]
author = "Anton Podviaznikov"
author_email = "anton@podviaznikov.com"
tagline = "programmer, observer, citizen of the world"
license = "Attribution, share alike"
logo_text_color = "#333"
logo_text_classname = "dark-gray"
logo_bg_color = "#e8fdf5"
logo_bg_classname = "washed-green"
[taxonomies]
color = "colors"
license = "licenses"
location = "locations"
person = "people"
tag = "tags"
