baseURL = "https://podviaznikov.com"
languageCode = "en-us"
title = "My site!!!"
theme = "montaigne"

[params]
author = "Anton Podviaznikov"
authorEmail = "anton@podviaznikov.com"
tagline = "Hello222"
